apiVersion: v1
kind: Service
metadata:
  name: quardio-node-service
  labels:
   name: quardio-node-service
   app: quardio-node-service
spec:
 ports:
 - port: 49160
   targetPort: 49160
 selector:
   name: quardio-node
   app: quardio-node
