apiVersion: v1
kind: Service
metadata:
  name: quardio-again-service
  labels:
    name: quardio-again-service
    app: demo-quardio-again-app

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
      name: quardio-again--app-pod
      app: demo-quardio-again-app
